

#ifndef P1_RUNNING_CODE_H
#define P1_RUNNING_CODE_H
#define PROCESSING 0
#define SINGLE_LEFT_REDIRECTION 1
#define SINGLE_RIGHT_REDIRECTION 2
#define DOUBLE_RIGHT_REDIRECTION 3
#define END_OF_LINE 10
#define PIPE 11
#define PIPE_END_OF_LINE 1110
#define EXIT 482477
#endif //P1_RUNNING_CODE_H
